-- =====================================================================
-- Pharmacy Management System - Supabase Database Schema
-- Run this script in your Supabase Project: SQL Editor -> New Query -> Run
-- =====================================================================

-- 1. Create 'medicines' Table
CREATE TABLE IF NOT EXISTS public.medicines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(100) NOT NULL,
    stock INTEGER NOT NULL DEFAULT 0 CHECK (stock >= 0),
    price NUMERIC(10, 2) NOT NULL DEFAULT 0.00 CHECK (price >= 0),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create 'orders' Table
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    customer_name VARCHAR(255),
    status VARCHAR(50) DEFAULT 'Processing',
    total_price NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    order_date TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create 'order_items' Table
CREATE TABLE IF NOT EXISTS public.order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
    medicine_id BIGINT NOT NULL REFERENCES public.medicines(id) ON DELETE RESTRICT,
    quantity INTEGER NOT NULL CHECK (quantity > 0)
);

-- 4. Indexes for fast query performance
CREATE INDEX IF NOT EXISTS idx_medicines_name ON public.medicines (name);
CREATE INDEX IF NOT EXISTS idx_orders_date ON public.orders (order_date DESC);
CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON public.order_items (order_id);
CREATE INDEX IF NOT EXISTS idx_order_items_medicine_id ON public.order_items (medicine_id);

-- 5. Enable Row Level Security (RLS)
ALTER TABLE public.medicines ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;

-- The backend uses the service-role key, which bypasses RLS. Do not add
-- permissive anon policies; add authenticated policies if direct client access is introduced.
DROP POLICY IF EXISTS "Allow all access to medicines" ON public.medicines;
DROP POLICY IF EXISTS "Allow all access to orders" ON public.orders;
DROP POLICY IF EXISTS "Allow all access to order_items" ON public.order_items;

-- 6. Seed Initial Sample Medicines
INSERT INTO public.medicines (name, category, stock, price)
SELECT sample.name, sample.category, sample.stock, sample.price
FROM (VALUES
    ('DOLO 650', 'Tablet', 300, 40.00),
    ('Paracetamol 500mg', 'Tablet', 250, 25.00),
    ('Cough Syrup (Benadryl)', 'Syrup', 180, 85.00),
    ('Cipla Cetirizine 10mg', 'Tablet', 400, 20.00),
    ('Amoxicillin 500mg', 'Capsule', 150, 95.00),
    ('Azithromycin 500mg', 'Tablet', 120, 115.00),
    ('Omeprazole 20mg', 'Capsule', 200, 55.00),
    ('Ibuprofen 400mg', 'Tablet', 175, 35.00),
    ('Vitamin C + Zinc', 'Tablet', 350, 60.00),
    ('Pantoprazole 40mg', 'Tablet', 220, 75.00)
) AS sample(name, category, stock, price)
WHERE NOT EXISTS (
    SELECT 1
    FROM public.medicines existing
    WHERE existing.name = sample.name
);

-- 7. Stored procedure for atomic orders with stock validation
CREATE OR REPLACE FUNCTION public.place_order_atomic(
    p_customer_name TEXT,
    p_user_id BIGINT,
    p_items JSONB
)
RETURNS JSONB
LANGUAGE plpgsql
AS $$
DECLARE
    v_order_id BIGINT;
    v_total_price NUMERIC(10, 2) := 0;
    v_item JSONB;
    v_med_id BIGINT;
    v_qty INT;
    v_price NUMERIC(10, 2);
    v_stock INT;
    v_med_name TEXT;
BEGIN
    IF p_items IS NULL OR jsonb_typeof(p_items) <> 'array' OR jsonb_array_length(p_items) = 0 THEN
        RAISE EXCEPTION 'Order must contain at least one item';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM jsonb_array_elements(p_items) AS entries(entry)
        WHERE entry->>'medicine_id' IS NULL
            OR entry->>'quantity' IS NULL
            OR (entry->>'quantity')::INT <= 0
    ) THEN
        RAISE EXCEPTION 'Each order item must include a medicine ID and a positive quantity';
    END IF;

    -- Lock rows in a stable order and aggregate duplicate medicine lines before checking stock.
    PERFORM m.id
    FROM public.medicines m
    JOIN (
        SELECT (entry->>'medicine_id')::BIGINT AS medicine_id
        FROM jsonb_array_elements(p_items) AS entries(entry)
        GROUP BY 1
    ) requested ON requested.medicine_id = m.id
    ORDER BY m.id
    FOR UPDATE OF m;

    FOR v_item IN
        SELECT jsonb_build_object(
            'medicine_id', (entry->>'medicine_id')::BIGINT,
            'quantity', SUM((entry->>'quantity')::INT)
        )
        FROM jsonb_array_elements(p_items) AS entries(entry)
        GROUP BY (entry->>'medicine_id')::BIGINT
        ORDER BY (entry->>'medicine_id')::BIGINT
    LOOP
        v_med_id := (v_item->>'medicine_id')::BIGINT;
        v_qty := (v_item->>'quantity')::INT;

        IF v_med_id IS NULL OR v_qty IS NULL OR v_qty <= 0 THEN
            RAISE EXCEPTION 'Each order item must include a medicine ID and a positive quantity';
        END IF;

        SELECT name, price, stock INTO v_med_name, v_price, v_stock
        FROM public.medicines
        WHERE id = v_med_id;

        IF NOT FOUND THEN
            RAISE EXCEPTION 'Medicine with ID % not found', v_med_id;
        END IF;

        IF v_stock < v_qty THEN
            RAISE EXCEPTION 'Medicine % is out of stock (Available: %, Requested: %)', v_med_name, v_stock, v_qty;
        END IF;

        v_total_price := v_total_price + (v_price * v_qty);
    END LOOP;

    -- 2. Insert into orders
    INSERT INTO public.orders (user_id, customer_name, total_price, status)
    VALUES (p_user_id, p_customer_name, v_total_price, 'Processing')
    RETURNING id INTO v_order_id;

    -- 3. Insert order items & deduct stock
    FOR v_item IN
        SELECT jsonb_build_object(
            'medicine_id', (entry->>'medicine_id')::BIGINT,
            'quantity', SUM((entry->>'quantity')::INT)
        )
        FROM jsonb_array_elements(p_items) AS entries(entry)
        GROUP BY (entry->>'medicine_id')::BIGINT
        ORDER BY (entry->>'medicine_id')::BIGINT
    LOOP
        v_med_id := (v_item->>'medicine_id')::BIGINT;
        v_qty := (v_item->>'quantity')::INT;

        INSERT INTO public.order_items (order_id, medicine_id, quantity)
        VALUES (v_order_id, v_med_id, v_qty);

        UPDATE public.medicines
        SET stock = stock - v_qty, updated_at = NOW()
        WHERE id = v_med_id;
    END LOOP;

    RETURN jsonb_build_object(
        'message', 'Order Placed Successfully',
        'order_id', v_order_id,
        'total_price', v_total_price
    );
END;
$$;
